### ISSUE TITLE
Instructions for setting language pairs unclear

### ISSUE THREAD

**Issue by warpling** [xfslove/alfred-language-configuration#3]
First of all thank you for making this! I'm excited to replace my current script that opens a google translate tab with my input. I translate a lot between one language at the moment but an having trouble setting the pair. I've brought up the script input in Alfred but when I type a pair I see the following:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/220240/73934047-fb575b80-48dd-11ea-8cbf-fd40a6e68ee5.png">

When I press return nothing happens. Perhaps I'm missing something. Would love to help improve the documentation if so!

**Comment by xfslove** [comment]
thanks for supporting. 

it seems like `trc` triggered the wrong workflow(alfred-google-translate instead of alfred-language-configuration). 

And seems like you just changed the hotkey of alfred-google-translate, right? 

Are you installed this workflow(alfred-language-configuration)?  If not, [you need do this.](https://github.com/xfslove/alfred-language-configuration/blob/master/README.md#install)

**Comment by warpling** [comment]
Ah you're totally right. I thought it had installed it but then must have gotten confused by the shared icon and old workflow!

**Comment by warpling** [comment]
Current archive isn't the latest version I think btw!

**Comment by warpling** [comment]
Still think I'm missing something though? Maybe once I understand I can help improve the README.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/220240/74233577-405b0380-4ccb-11ea-8cf6-d5526bda6d39.png">
<img width="623" alt="Screen Shot 2020-02-11 at 12 36 25 PM" src="https://user-images.githubusercontent.com/220240/74233583-43ee8a80-4ccb-11ea-9de4-ecbc1af360c1.png">

**Comment by xfslove** [comment]
actually，there are two workflows. The alfred-language-configuration with trc (like `trc en&nl` ) to configuration, and the alfred-google-translate to translate with tr (like `tr hello`).

**Comment by warpling** [comment]
Ohhhh. Mind if it try to improve the README with that?

**Comment by xfslove** [comment]
hi @warpling ，if you got the correct result as you expected. i'll close this issue.

**Comment by warpling** [comment]
Not sure what I’m doing wrong here but `tr` doesn’t trigger anything for me. Only `trc` does?

**Comment by xfslove** [comment]
could you post some captures of your workflows here (about what workflows you installed and your workflow configuration)?

**Comment by warpling** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/220240/75682375-a0731300-5c95-11ea-82af-f4709219944c.png">
This is all I have? I feel like maybe there's supposed to be a separate `tr.workflow` file somewhere but I haven't been able to find it.

**Comment by xfslove** [comment]
you also need to install [this one](https://github.com/xfslove/alfred-google-translate).

![snap](https://github.com/xfslove/alfred-google-translate/blob/master/media/env-config.png?raw=true)

**Comment by warpling** [comment]
Ohhhhhhhh—why are these separate repos??

**Comment by xfslove** [comment]
just for use the different keyword for different functions. Alfred just supported one script filter in one workflow. so I separate those.

**Comment by xfslove** [comment]
thanks for you participation. and I updated the readme to make it more clear. see the [install paragraph](https://github.com/xfslove/alfred-language-configuration#install).

and I'll close this issue if anything is right now.

**Comment by warpling** [comment]
Hope my PR helps too!

**Comment by xfslove** [comment]
@warpling Awesome! thats a great PR. please help me update the [alfred-google-translate](https://github.com/xfslove/alfred-google-translate) README if you want.

thanks a lot.

and i closed this issue now.
