### ISSUE TITLE
alfred4 用下载的方式安装 无法配置翻译

### ISSUE THREAD

**Issue by hermitcai** [xfslove/alfred-language-configuration#5]
alfred4 用下载的方式安装 无法配置翻译 只能将中文翻译成英文 无法将英文翻译成中文 这俩者我都是用下载文件的方式安装的 trc en&ch-CN 无效 trc ls 无效

**Comment by xfslove** [comment]
我抽空看看是不是包的问题

**Comment by hermitcai** [comment]
> 我抽空看看是不是包的问题

我设置好了 是我操作的方式不对 谢谢 您帮我看看我提的另外一个case额
