### ISSUE TITLE
能正常翻墙，但翻译的时候始终卡在 translating...

### ISSUE THREAD

**Issue by hy4015** [xfslove/alfred-language-configuration#7]
能正常翻墙，但翻译的时候始终卡在 translating...
请问如何解决，谢谢！

**Comment by xfslove** [comment]
workflow需要单独配置代理的，你可以用google.translate.cn。可以看下[readme](https://github.com/xfslove/alfred-google-translate#environment-variables)如何配置

**Comment by xfslove** [comment]
如果没问题我就先把这个issue关闭了，还有问题可以重新打开或者重新开一个
